USE ROLE ACCOUNTADMIN;
 
CREATE OR REPLACE DATABASE INSTACART_DB;

-- RAW / BRONZE
CREATE SCHEMA IF NOT EXISTS INSTACART_DB.INSTA_RAW;
USE SCHEMA INSTACART_DB.INSTA_RAW;

CREATE OR REPLACE TABLE SALES_RAW (
    PRODUCT_ID              NUMBER,
    SALE_DATE               DATE,
    SALES_REP               STRING,
    REGION                  STRING,
    SALES_AMOUNT            NUMBER(12,2),
    QUANTITY_SOLD           NUMBER,
    PRODUCT_CATEGORY        STRING,
    UNIT_COST               NUMBER(12,2),
    UNIT_PRICE              NUMBER(12,2),
    CUSTOMER_TYPE           STRING,
    DISCOUNT                NUMBER(5,2),
    PAYMENT_METHOD          STRING,
    SALES_CHANNEL           STRING,
    REGION_AND_SALES_REP    STRING,
    _LOADED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Storage integration
CREATE OR REPLACE STORAGE INTEGRATION AZURE_SALES_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = AZURE
    ENABLED = TRUE
    AZURE_TENANT_ID = 'your_tenant_id'
    STORAGE_ALLOWED_LOCATIONS = (
        'your_blob_url'
    );

 DESC STORAGE INTEGRATION AZURE_SALES_INT;

-- Notification integration (Snowpipe auto-ingest trigger)
CREATE OR REPLACE NOTIFICATION INTEGRATION AZURE_NOTIF_INT
    TYPE = QUEUE
    ENABLED = TRUE
    NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
    AZURE_STORAGE_QUEUE_PRIMARY_URI = 'your_queue_url'
    AZURE_TENANT_ID = 'your_tenant_id';
 
DESC NOTIFICATION INTEGRATION AZURE_NOTIF_INT;


-- file format sales_csv
CREATE OR REPLACE FILE FORMAT FF_SALES_CSV
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    DATE_FORMAT = 'AUTO';

-- Stage SALES_STAGE_1
CREATE OR REPLACE STAGE SALES_STAGE_1
    URL = 'your_blob_url'
    STORAGE_INTEGRATION = AZURE_SALES_INT
    FILE_FORMAT = FF_SALES_CSV;

LIST @SALES_STAGE_1;

-- Pipe (auto-ingest via the notification integration)
CREATE OR REPLACE PIPE AutoSnowPipe1
    AUTO_INGEST = TRUE
    INTEGRATION = AZURE_NOTIF_INT
AS
    COPY INTO INSTACART_DB.INSTA_RAW.SALES_RAW (
        PRODUCT_ID, SALE_DATE, SALES_REP, REGION, SALES_AMOUNT, QUANTITY_SOLD,
        PRODUCT_CATEGORY, UNIT_COST, UNIT_PRICE, CUSTOMER_TYPE, DISCOUNT,
        PAYMENT_METHOD, SALES_CHANNEL, REGION_AND_SALES_REP
    )
    FROM @SALES_STAGE_1
    FILE_FORMAT = (FORMAT_NAME = FF_SALES_CSV)
    ON_ERROR = 'CONTINUE';   -- one bad row won't block the whole file



 SELECT SYSTEM$PIPE_STATUS('AutoSnowPipe1');

 SELECT * FROM SALES_RAW;

  ALTER PIPE AutoSnowPipe1 REFRESH;
SELECT * FROM INSTACART_DB.INSTA_RAW.SALES_RAW;

 TRUNCATE TABLE SALES_RAW;

 SELECT FILE_NAME, STATUS, FIRST_ERROR_MESSAGE, LAST_LOAD_TIME
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME=>'SALES_RAW',
    START_TIME=>DATEADD('hour',-2,CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;

SELECT SYSTEM$STREAM_HAS_DATA('INSTACART_DB.INSTA_RAW.RAW_SALES_STREAM');

SHOW TASKS IN SCHEMA INSTACART_DB.INSTA_RAW;

ALTER TASK INSTACART_DB.INSTA_RAW.LOAD_SALES_GOLD RESUME;
ALTER TASK INSTACART_DB.INSTA_RAW.LOAD_SALES_SILVER RESUME;

SELECT SYSTEM$STREAM_HAS_DATA('INSTACART_DB.INSTA_RAW.RAW_SALES_STREAM');
SELECT COUNT(*) FROM INSTACART_DB.INSTA_SILVER.SALES_CLEAN;
SELECT * FROM INSTACART_DB.INSTA_GOLD.V_SALES_KPIS;

SELECT DISTINCT _FILE_NAME, MIN(_LOADED_AT) AS first_loaded, COUNT(*) AS row_count
FROM INSTACART_DB.INSTA_RAW.SALES_RAW
GROUP BY _FILE_NAME
ORDER BY first_loaded DESC;

-- TRUNCATE TABLE INSTACART_DB.INSTA_RAW.SALES_RAW;
-- TRUNCATE TABLE INSTACART_DB.INSTA_SILVER.SALES_CLEAN;
-- TRUNCATE TABLE INSTACART_DB.INSTA_GOLD.SALES_KPIS_BY_REGION_CATEGORY;

SELECT REGION, SUM(TOTAL_PROFIT) AS TOTAL_PROFIT_PER_REGION
FROM INSTACART_DB.INSTA_GOLD.V_SALES_KPIS
GROUP BY REGION;

SELECT CURRENT_ACCOUNT(), CURRENT_USER();
SELECT CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT();
SELECT CURRENT_REGION();
SELECT CURRENT_ACCOUNT_NAME();