USE ROLE ACCOUNTADMIN;
USE INSTACART_DB;

CREATE SCHEMA IF NOT EXISTS INSTACART_DB.INSTA_GOLD;

CREATE OR REPLACE STREAM INSTACART_DB.INSTA_SILVER.SALES_CLEAN_STREAM
    ON TABLE INSTACART_DB.INSTA_SILVER.SALES_CLEAN;

CREATE OR REPLACE TABLE INSTACART_DB.INSTA_GOLD.SALES_KPIS_BY_REGION_CATEGORY (
    REGION              STRING,
    PRODUCT_CATEGORY    STRING,
    TOTAL_REVENUE       NUMBER(18,2),
    TOTAL_UNITS_SOLD    NUMBER,
    TOTAL_PROFIT        NUMBER(18,2),
    TOTAL_DISCOUNT_SUM  NUMBER(18,2),   -- kept as a sum, not an avg, so it can be aggregated correctly later
    ORDER_COUNT         NUMBER,
    LAST_UPDATED_AT     TIMESTAMP_NTZ
);



CREATE OR REPLACE TASK INSTACART_DB.INSTA_RAW.LOAD_SALES_GOLD
    WAREHOUSE = COMPUTE_WH
    AFTER INSTACART_DB.INSTA_RAW.LOAD_SALES_SILVER
    WHEN SYSTEM$STREAM_HAS_DATA('INSTACART_DB.INSTA_SILVER.SALES_CLEAN_STREAM')
AS
MERGE INTO INSTACART_DB.INSTA_GOLD.SALES_KPIS_BY_REGION_CATEGORY tgt
USING (
    SELECT
        REGION,
        PRODUCT_CATEGORY,
        SUM(SALES_AMOUNT)                                                    AS delta_revenue,
        SUM(QUANTITY_SOLD)                                                   AS delta_units,
        -- DISCOUNT is a fraction (0.09 = 9% off), not 0-100, so no /100 here
        SUM((UNIT_PRICE - UNIT_COST) * QUANTITY_SOLD * (1 - DISCOUNT)) AS delta_profit,
        SUM(DISCOUNT)                                                        AS delta_discount_sum,
        COUNT(*)                                                             AS delta_orders
    FROM INSTACART_DB.INSTA_SILVER.SALES_CLEAN_STREAM
    WHERE METADATA$ACTION = 'INSERT'
    GROUP BY REGION, PRODUCT_CATEGORY
) src
ON tgt.REGION = src.REGION AND tgt.PRODUCT_CATEGORY = src.PRODUCT_CATEGORY
WHEN MATCHED THEN UPDATE SET
    TOTAL_REVENUE      = tgt.TOTAL_REVENUE + src.delta_revenue,
    TOTAL_UNITS_SOLD    = tgt.TOTAL_UNITS_SOLD + src.delta_units,
    TOTAL_PROFIT        = tgt.TOTAL_PROFIT + src.delta_profit,
    TOTAL_DISCOUNT_SUM  = tgt.TOTAL_DISCOUNT_SUM + src.delta_discount_sum,
    ORDER_COUNT          = tgt.ORDER_COUNT + src.delta_orders,
    LAST_UPDATED_AT       = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    REGION, PRODUCT_CATEGORY, TOTAL_REVENUE, TOTAL_UNITS_SOLD, TOTAL_PROFIT,
    TOTAL_DISCOUNT_SUM, ORDER_COUNT, LAST_UPDATED_AT
) VALUES (
    src.REGION, src.PRODUCT_CATEGORY, src.delta_revenue, src.delta_units,
    src.delta_profit, src.delta_discount_sum, src.delta_orders, CURRENT_TIMESTAMP()
);
 
-- A view for "average discount"
-- average directly (TOTAL_DISCOUNT_SUM / ORDER_COUNT is always correct,
-- unlike averaging two averages together).
CREATE OR REPLACE VIEW INSTACART_DB.INSTA_GOLD.V_SALES_KPIS AS
SELECT
    REGION,
    PRODUCT_CATEGORY,
    TOTAL_REVENUE,
    TOTAL_UNITS_SOLD,
    TOTAL_PROFIT,
    ROUND(TOTAL_DISCOUNT_SUM / NULLIF(ORDER_COUNT, 0), 2) AS AVG_DISCOUNT,
    ORDER_COUNT,
    LAST_UPDATED_AT
FROM INSTACART_DB.INSTA_GOLD.SALES_KPIS_BY_REGION_CATEGORY;


SHOW PIPES;
SHOW STREAMS;
SHOW TASKS;

 
SELECT * FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'INSTACART_DB.INSTA_SILVER.SALES_CLEAN',
        START_TIME => DATEADD('hour', -2, CURRENT_TIMESTAMP())
    )
) ORDER BY LAST_LOAD_TIME DESC;

 
SELECT * FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME => 'LOAD_SALES_SILVER')
) ORDER BY SCHEDULED_TIME DESC;


SELECT * FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME => 'LOAD_SALES_GOLD')
) ORDER BY SCHEDULED_TIME DESC;

SHOW STREAMS IN DATABASE INSTACART_DB;
SHOW TASKS IN DATABASE INSTACART_DB;
SHOW PIPES IN DATABASE INSTACART_DB;

SELECT SYSTEM$STREAM_HAS_DATA('INSTACART_DB.INSTA_RAW.RAW_SALES_STREAM');
SELECT SYSTEM$STREAM_HAS_DATA('INSTACART_DB.INSTA_SILVER.SALES_CLEAN_STREAM');

SELECT COUNT(*) FROM INSTACART_DB.INSTA_RAW.SALES_RAW;
SELECT * FROM INSTACART_DB.INSTA_SILVER.SALES_CLEAN;          
SELECT * FROM V_SALES_KPIS;        

CREATE OR REPLACE STREAM INSTACART_DB.INSTA_RAW.RAW_SALES_STREAM
    ON TABLE INSTACART_DB.INSTA_RAW.SALES_RAW;
CREATE OR REPLACE STREAM INSTACART_DB.INSTA_SILVER.SALES_CLEAN_STREAM
    ON TABLE INSTACART_DB.INSTA_SILVER.SALES_CLEAN;

SELECT COUNT(*) FROM INSTACART_DB.INSTA_RAW.SALES_RAW;        
SELECT COUNT(*) FROM INSTACART_DB.INSTA_SILVER.SALES_CLEAN;   
SELECT COUNT(*) FROM INSTACART_DB.INSTA_GOLD.SALES_KPIS_BY_REGION_CATEGORY;  