USE ROLE ACCOUNTADMIN;

USE INSTACART_DB;

CREATE SCHEMA IF NOT EXISTS INSTACART_DB.INSTA_SILVER;

CREATE OR REPLACE TABLE INSTACART_DB.INSTA_SILVER.SALES_CLEAN (
    PRODUCT_ID              NUMBER,
    SALE_DATE               DATE,
    SALES_REP                STRING,
    REGION                   STRING,
    SALES_AMOUNT             NUMBER(12,2),
    QUANTITY_SOLD            NUMBER,
    PRODUCT_CATEGORY         STRING,
    UNIT_COST                NUMBER(12,2),
    UNIT_PRICE               NUMBER(12,2),
    CUSTOMER_TYPE             STRING,
    DISCOUNT                 NUMBER(5,2),
    PAYMENT_METHOD            STRING,
    SALES_CHANNEL             STRING,
    REGION_AND_SALES_REP      STRING,
    _LOADED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STREAM INSTACART_DB.INSTA_RAW.RAW_SALES_STREAM
    ON TABLE INSTACART_DB.INSTA_RAW.SALES_RAW;

CREATE OR REPLACE TASK INSTACART_DB.INSTA_RAW.LOAD_SALES_SILVER
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('INSTACART_DB.INSTA_RAW.RAW_SALES_STREAM')
AS
    INSERT INTO INSTACART_DB.INSTA_SILVER.SALES_CLEAN (
        PRODUCT_ID, SALE_DATE, SALES_REP, REGION, SALES_AMOUNT, QUANTITY_SOLD,
        PRODUCT_CATEGORY, UNIT_COST, UNIT_PRICE, CUSTOMER_TYPE, DISCOUNT,
        PAYMENT_METHOD, SALES_CHANNEL, REGION_AND_SALES_REP
    )
    SELECT
        PRODUCT_ID,
        SALE_DATE,
        UPPER(TRIM(SALES_REP)),
        UPPER(TRIM(REGION)),
        SALES_AMOUNT,
        QUANTITY_SOLD,
        UPPER(TRIM(PRODUCT_CATEGORY)),
        UNIT_COST,
        UNIT_PRICE,
        UPPER(TRIM(CUSTOMER_TYPE)),
        DISCOUNT,
        UPPER(TRIM(PAYMENT_METHOD)),
        UPPER(TRIM(SALES_CHANNEL)),
        UPPER(TRIM(REGION)) || '-' || UPPER(TRIM(SALES_REP))   -- recomputed, not trusted from source
    FROM INSTACART_DB.INSTA_RAW.RAW_SALES_STREAM
    WHERE METADATA$ACTION = 'INSERT'
      AND PRODUCT_ID IS NOT NULL
      AND SALE_DATE IS NOT NULL
      AND SALES_AMOUNT >= 0
      AND QUANTITY_SOLD > 0;

